[config]
schemaVersion = "0.0.1"

[package]
namespace = "xhayper"
name = "COTL_Multiplayer"
versionNumber = "0.1.0"
description = "Cult of the Lamb... but multiplayer!"
websiteUrl = "https://github.com/xhayper/COTL_Multiplayer"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_CultOfTheLamb = "5.4.21"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "bin/Release/COTL_Multiplayer/COTL_Multiplayer.dll"
target = "plugins/io.github.xhayper.COTL_Multiplayer/COTL_Multiplayer.dll"

[publish]
repository = "https://cult-of-the-lamb.thunderstore.io"
communities = ["cult-of-the-lamb"]
categories = ["misc"]
